# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GiH8gLvNItTAPw7qbuomaljHDOF4Ep0U
"""

import numpy as np
import matplotlib.pyplot as plt

# Sinus grafigi uchun ma'lumotlar
x = np.linspace(0, 10, 100)  # 0 dan 10 gacha bo'lgan qiymatlar
y = np.sin(x)  # Sinus funksiyasi

# Tasodifiy nuqtalar uchun ma'lumotlar
x_scatter = np.random.uniform(0, 10, 50)  # 0 dan 10 gacha bo'lgan 50 tasodifiy nuqta
y_scatter = np.random.uniform(0, 10, 50)  # 0 dan 10 gacha bo'lgan 50 tasodifiy nuqta

# Grafiklarni yonma-yon joylashtirish
fig, axs = plt.subplots(1, 2, figsize=(12, 5))  # 1 qator, 2 ta ustunli grafik

# 1-grafik: Sinus funksiyasi
axs[0].plot(x, y, color='blue', label='Sinus(x)')
axs[0].set_title('Sinus Funktsiyasi Grafigi')
axs[0].set_xlabel('X qiymatlari')
axs[0].set_ylabel('Y qiymatlari')
axs[0].legend()  # Legend qo'shish
axs[0].grid(True)  # Setka qo'shish

# 2-grafik: Tasodifiy nuqtalar scatter grafigi
axs[1].scatter(x_scatter, y_scatter, color='blue', label='Nuqtalar')
axs[1].set_title('Tasodifiy Nuqtalar Scatter Grafigi')
axs[1].set_xlabel('X qiymatlari')
axs[1].set_ylabel('Y qiymatlari')
axs[1].legend()  # Legend qo'shish
axs[1].grid(True)  # Setka qo'shish

# Grafiklarni ko'rsatish
plt.tight_layout()  # Grafiklar orasidagi bo'shliqni boshqarish
plt.show()